# Generated by Django 5.1 on 2024-09-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='/media.png', upload_to='images/user/profile/covers'),
        ),
    ]
