# Generated by Django 5.1 on 2024-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='/user.png', upload_to='images/user/profile/covers'),
        ),
    ]
