# Generated by Django 5.1 on 2024-09-07 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_series_seriespost'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
